platform :android do
  desc 'Bump version and Build the Android application.'
  lane :bump_build_version do
    path = '../android/app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close

    repo_clean = `git status --porcelain`.empty?
    if !repo_clean
      git_commit(path: 'android/app/build.gradle', message: 'Bump android build')
    end
    git_pull
    push_to_git_remote
  end

  lane :build do
     gradle(task: 'clean', project_dir: 'android/')
     gradle(
        task: 'assemble',
        build_type: 'release',
        project_dir: 'android/',
        flavor: ENV["ANDROID_FLAVOUR"]
     )
  end
end
